In [1]:
import pandas as pd

df = pd.read_csv(r"D:\PandasYouTubeSeries-main\countries of the world.csv", sep=';', encoding='utf-8')

df.columns = df.columns.str.strip()

df['Country'] = df['Country'].str.strip()
df['Region'] = df['Region'].str.strip()

from IPython.display import display
display(df.head(228))

            Country                Region
0       Afghanistan  ASIA (EX. NEAR EAST)
1           Albania        EASTERN EUROPE
2           Algeria       NORTHERN AFRICA
3    American Samoa               OCEANIA
4           Andorra        WESTERN EUROPE
..              ...                   ...
222       West Bank             NEAR EAST
223  Western Sahara       NORTHERN AFRICA
224           Yemen             NEAR EAST
225          Zambia    SUB-SAHARAN AFRICA
226        Zimbabwe    SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [6]:
df = pd.read_excel(r"D:\PandasYouTubeSeries-main\world_population_excel_workbook.xlsx")
df.head()
from IPython.display import display
display(df.head(234))

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (kmÂ²),Density (per kmÂ²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El AaiÃºn,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

In [9]:
df2 = pd.read_excel(r"D:\PandasYouTubeSeries-main\world_population_excel_workbook.xlsx", sheet_name = 'Sheet1')
df2.head()
from IPython.display import display
display(df2.head(234))

     Rank CCA3            Country           Capital
0      36  AFG        Afghanistan             Kabul
1     138  ALB            Albania            Tirana
2      34  DZA            Algeria           Algiers
3     213  ASM     American Samoa         Pago Pago
4     203  AND            Andorra  Andorra la Vella
..    ...  ...                ...               ...
229   226  WLF  Wallis and Futuna          Mata-Utu
230   172  ESH     Western Sahara         El AaiÃºn
231    46  YEM              Yemen             Sanaa
232    63  ZMB             Zambia            Lusaka
233    74  ZWE           Zimbabwe            Harare

[234 rows x 4 columns]

In [13]:
pd.set_option('display.max.rows', None)
pd.set_option('display.max.columns', 40)

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     234 non-null    int64
 1   CCA3     234 non-null    object
 2   Country  234 non-null    object
 3   Capital  234 non-null    object
dtypes: int64(1), object(3)
memory usage: 7.4+ KB

In [6]:
df2 = pd.read_excel(r"D:\PandasYouTubeSeries-main\world_population_excel_workbook.xlsx", sheet_name = 'Sheet1')
df2.shape

(234, 4)

In [7]:
df2.head(10)

   Rank CCA3              Country           Capital
0    36  AFG          Afghanistan             Kabul
1   138  ALB              Albania            Tirana
2    34  DZA              Algeria           Algiers
3   213  ASM       American Samoa         Pago Pago
4   203  AND              Andorra  Andorra la Vella
5    42  AGO               Angola            Luanda
6   224  AIA             Anguilla        The Valley
7   201  ATG  Antigua and Barbuda    Saint Johnâ€™s
8    33  ARG            Argentina      Buenos Aires
9   140  ARM              Armenia           Yerevan

In [8]:
df2.tail(10)

     Rank CCA3            Country       Capital
224    43  UZB         Uzbekistan      Tashkent
225   181  VUT            Vanuatu     Port-Vila
226   234  VAT       Vatican City  Vatican City
227    51  VEN          Venezuela       Caracas
228    16  VNM            Vietnam         Hanoi
229   226  WLF  Wallis and Futuna      Mata-Utu
230   172  ESH     Western Sahara     El AaiÃºn
231    46  YEM              Yemen         Sanaa
232    63  ZMB             Zambia        Lusaka
233    74  ZWE           Zimbabwe        Harare

In [14]:
df2['Rank']

0       36
1      138
2       34
3      213
4      203
5       42
6      224
7      201
8       33
9      140
10     198
11      55
12      99
13      91
14     176
15     154
16       8
17     186
18      96
19      81
20     177
21      77
22     206
23     165
24      80
25     137
26     144
27       7
28     221
29     175
30     108
31      58
32      78
33      73
34      53
35      39
36     171
37     205
38     117
39      69
40      65
41       1
42      28
43     163
44     223
45     124
46     130
47      85
48     189
49     158
50      88
51     115
52     160
53     204
54      84
55      15
56      67
57      14
58     112
59     152
60     132
61     156
62     159
63      12
64     231
65     209
66     162
67     118
68      23
69     184
70     183
71     146
72     142
73     131
74      19
75      47
76     219
77      90
78     208
79     193
80     178
81     191
82      68
83     207
84      75
85     149
86     164
87      82
88      89
89     104
90      94
91     179
92       2
93       4
94      17
95      35
96     125
97     202
98      98
99      25
100     52
101    139
102     11
103    195
104     83
105     66
106     27
107    192
108    129
109    110
110    103
111    151
112    119
113    147
114    121
115    107
116    216
117    141
118    168
119    167
120     50
121     62
122     45
123    174
124     59
125    173
126    215
127    180
128    126
129    157
130    182
131     10
132    194
133    135
134    217
135    134
136    169
137    230
138     40
139     48
140     26
141    145
142    225
143     49
144     71
145    185
146    123
147    106
148     54
149      6
150    232
151     56
152    150
153    210
154    120
155    127
156      5
157    222
158    122
159    128
160     93
161    109
162     44
163     13
164     37
165     92
166    136
167    143
168    114
169    161
170     64
171      9
172     76
173    228
174    211
175    190
176    220
177    229
178    199
179    188
180    218
181    187
182     41
183     72
184    105
185    196
186    102
187    113
188    214
189    116
190    148
191    166
192     70
193     24
194     29
195     86
196     30
197     61
198     32
199    170
200     87
201    101
202     60
203     57
204     95
205     22
206     20
207    155
208    100
209    233
210    197
211    153
212     79
213     18
214    111
215    212
216    227
217     31
218     38
219     97
220     21
221      3
222    200
223    133
224     43
225    181
226    234
227     51
228     16
229    226
230    172
231     46
232     63
233     74
Name: Rank, dtype: int64

In [10]:
df2.loc[224]

Rank               43
CCA3              UZB
Country    Uzbekistan
Capital      Tashkent
Name: 224, dtype: object